root: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
env:
  browser: true
parserOptions:
  sourceType: script
rules:
  no-underscore-dangle: off
  no-plusplus: off
  no-param-reassign: off
  no-restricted-syntax: off
  no-restricted-globals: off

  arrow-body-style: off
  default-case: off
  prefer-const:
    - error
    - destructuring: all
  strict:
    - error
    - safe

  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
