sudo: false
language: node_js

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

node_js:
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - '0.10.26'

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
